// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtE4nHUgIvQTySs5xxj66EkKXMwItOOCw',
    appId: '1:233759056468:web:11075e6acc2012c49bc3c1',
    messagingSenderId: '233759056468',
    projectId: 'globalchatdyno',
    authDomain: 'globalchatdyno.firebaseapp.com',
    storageBucket: 'globalchatdyno.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMHEDKCpfJnq3G33ERNpsUuIcS6nRcb4c',
    appId: '1:233759056468:android:61c854ac02f6bb219bc3c1',
    messagingSenderId: '233759056468',
    projectId: 'globalchatdyno',
    storageBucket: 'globalchatdyno.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLzn0NJk7DHDeulHJNz3AWoffbwb4Ls4',
    appId: '1:233759056468:ios:9e42745215296baf9bc3c1',
    messagingSenderId: '233759056468',
    projectId: 'globalchatdyno',
    storageBucket: 'globalchatdyno.appspot.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLzn0NJk7DHDeulHJNz3AWoffbwb4Ls4',
    appId: '1:233759056468:ios:9e42745215296baf9bc3c1',
    messagingSenderId: '233759056468',
    projectId: 'globalchatdyno',
    storageBucket: 'globalchatdyno.appspot.com',
    iosBundleId: 'com.example.loginui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtE4nHUgIvQTySs5xxj66EkKXMwItOOCw',
    appId: '1:233759056468:web:178b70b55d2874b49bc3c1',
    messagingSenderId: '233759056468',
    projectId: 'globalchatdyno',
    authDomain: 'globalchatdyno.firebaseapp.com',
    storageBucket: 'globalchatdyno.appspot.com',
  );
}
